/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Projected from `packages/shared-schemas/src/shared_schemas/metrics.py` by
 * `packages/shared-schemas/generate_catalog.py`. Change the metric there and run
 * `task metrics:generate`; editing this file only makes the two disagree, which is
 * the failure the registry was introduced to prevent.
 */

export type Aggregation = "average" | "sum" | "last" | "max";

export interface MetricDefinition {
  key: string;
  /** Unit of every value stored under this key. Empty string = carried in metadata. */
  unit: string;
  aggregation: Aggregation;
  category: string;
  labelDe: string;
  labelEn: string;
  sources: string[];
  aliases: string[];
  plausibleMin: number | null;
  plausibleMax: number | null;
  precision: number;
}

export interface MetricNamespace {
  prefix: string;
  category: string;
  labelDe: string;
  labelEn: string;
}

export const METRIC_CATALOG: Record<string, MetricDefinition> = {
  "steps": {
    key: "steps",
    unit: "count",
    aggregation: "sum",
    category: "activity",
    labelDe: "Schritte",
    labelEn: "Steps",
    sources: ["apple_health"],
    aliases: ["step_count", "steps_count"],
    plausibleMin: 0.0,
    plausibleMax: 200000.0,
    precision: 0,
  },
  "distance": {
    key: "distance",
    unit: "km",
    aggregation: "sum",
    category: "activity",
    labelDe: "Zurückgelegte Distanz",
    labelEn: "Distance travelled",
    sources: ["apple_health"],
    aliases: ["distance_walking_running", "walking_running_distance"],
    plausibleMin: 0.0,
    plausibleMax: 500.0,
    precision: 2,
  },
  "energy_active": {
    key: "energy_active",
    unit: "kcal",
    aggregation: "sum",
    category: "activity",
    labelDe: "Aktive Energie",
    labelEn: "Active energy",
    sources: ["apple_health"],
    aliases: ["active_energy", "active_energy_burned"],
    plausibleMin: 0.0,
    plausibleMax: 15000.0,
    precision: 0,
  },
  "energy_resting": {
    key: "energy_resting",
    unit: "kcal",
    aggregation: "sum",
    category: "activity",
    labelDe: "Grundumsatz",
    labelEn: "Resting energy",
    sources: ["apple_health"],
    aliases: ["resting_energy", "basal_energy_burned"],
    plausibleMin: 0.0,
    plausibleMax: 6000.0,
    precision: 0,
  },
  "energy_total": {
    key: "energy_total",
    unit: "kcal",
    aggregation: "sum",
    category: "activity",
    labelDe: "Gesamtumsatz",
    labelEn: "Total energy burned",
    sources: ["whoop"],
    aliases: ["cycle_kilojoule"],
    plausibleMin: 0.0,
    plausibleMax: 20000.0,
    precision: 0,
  },
  "exercise_duration": {
    key: "exercise_duration",
    unit: "min",
    aggregation: "sum",
    category: "activity",
    labelDe: "Bewegungsminuten",
    labelEn: "Exercise time",
    sources: ["apple_health"],
    aliases: ["apple_exercise_time"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "stand_duration": {
    key: "stand_duration",
    unit: "min",
    aggregation: "sum",
    category: "activity",
    labelDe: "Stehminuten",
    labelEn: "Stand time",
    sources: ["apple_health"],
    aliases: ["apple_stand_time"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "flights_climbed": {
    key: "flights_climbed",
    unit: "count",
    aggregation: "sum",
    category: "activity",
    labelDe: "Etagen",
    labelEn: "Flights climbed",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 1000.0,
    precision: 0,
  },
  "whoop_strain": {
    key: "whoop_strain",
    unit: "index",
    aggregation: "max",
    category: "activity",
    labelDe: "Whoop Strain (Tag)",
    labelEn: "Whoop strain (day)",
    sources: ["whoop"],
    aliases: ["strain"],
    plausibleMin: 0.0,
    plausibleMax: 21.0,
    precision: 1,
  },
  "blood_pressure_systolic": {
    key: "blood_pressure_systolic",
    unit: "mmHg",
    aggregation: "average",
    category: "heart",
    labelDe: "Blutdruck systolisch",
    labelEn: "Blood pressure, systolic",
    sources: ["apple_health"],
    aliases: ["systolic"],
    plausibleMin: 50.0,
    plausibleMax: 260.0,
    precision: 0,
  },
  "blood_pressure_diastolic": {
    key: "blood_pressure_diastolic",
    unit: "mmHg",
    aggregation: "average",
    category: "heart",
    labelDe: "Blutdruck diastolisch",
    labelEn: "Blood pressure, diastolic",
    sources: ["apple_health"],
    aliases: ["diastolic"],
    plausibleMin: 30.0,
    plausibleMax: 180.0,
    precision: 0,
  },
  "heart_rate": {
    key: "heart_rate",
    unit: "bpm",
    aggregation: "average",
    category: "heart",
    labelDe: "Puls",
    labelEn: "Heart rate",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 20.0,
    plausibleMax: 250.0,
    precision: 0,
  },
  "heart_rate_average": {
    key: "heart_rate_average",
    unit: "bpm",
    aggregation: "average",
    category: "heart",
    labelDe: "Durchschnittspuls (Tag)",
    labelEn: "Average heart rate (day)",
    sources: ["whoop"],
    aliases: ["cycle_average_heart_rate"],
    plausibleMin: 20.0,
    plausibleMax: 200.0,
    precision: 0,
  },
  "heart_rate_max": {
    key: "heart_rate_max",
    unit: "bpm",
    aggregation: "max",
    category: "heart",
    labelDe: "Maximalpuls (Tag)",
    labelEn: "Maximum heart rate (day)",
    sources: ["whoop"],
    aliases: ["max_heart_rate"],
    plausibleMin: 20.0,
    plausibleMax: 250.0,
    precision: 0,
  },
  "heart_rate_resting": {
    key: "heart_rate_resting",
    unit: "bpm",
    aggregation: "average",
    category: "heart",
    labelDe: "Ruhepuls",
    labelEn: "Resting heart rate",
    sources: ["apple_health", "whoop"],
    aliases: ["resting_heart_rate", "resting_hr", "resting_heart_rate_bpm"],
    plausibleMin: 25.0,
    plausibleMax: 120.0,
    precision: 0,
  },
  "heart_rate_walking_average": {
    key: "heart_rate_walking_average",
    unit: "bpm",
    aggregation: "average",
    category: "heart",
    labelDe: "Gehpuls (Durchschnitt)",
    labelEn: "Walking heart rate average",
    sources: ["apple_health"],
    aliases: ["walking_heart_rate_average"],
    plausibleMin: 40.0,
    plausibleMax: 200.0,
    precision: 0,
  },
  "hrv_rmssd": {
    key: "hrv_rmssd",
    unit: "ms",
    aggregation: "average",
    category: "heart",
    labelDe: "HRV (RMSSD)",
    labelEn: "HRV (RMSSD)",
    sources: ["whoop"],
    aliases: ["hrv_rmssd_milli"],
    plausibleMin: 1.0,
    plausibleMax: 300.0,
    precision: 1,
  },
  "hrv_sdnn": {
    key: "hrv_sdnn",
    unit: "ms",
    aggregation: "average",
    category: "heart",
    labelDe: "HRV (SDNN)",
    labelEn: "HRV (SDNN)",
    sources: ["apple_health"],
    aliases: ["heart_rate_variability_sdnn", "hrv"],
    plausibleMin: 1.0,
    plausibleMax: 300.0,
    precision: 1,
  },
  "blood_oxygen": {
    key: "blood_oxygen",
    unit: "%",
    aggregation: "average",
    category: "heart",
    labelDe: "Sauerstoffsättigung",
    labelEn: "Blood oxygen",
    sources: ["apple_health", "whoop"],
    aliases: ["spo2_percentage", "spo2", "oxygen_saturation"],
    plausibleMin: 50.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "respiratory_rate": {
    key: "respiratory_rate",
    unit: "br/min",
    aggregation: "average",
    category: "heart",
    labelDe: "Atemfrequenz",
    labelEn: "Respiratory rate",
    sources: ["apple_health", "whoop"],
    aliases: [],
    plausibleMin: 4.0,
    plausibleMax: 60.0,
    precision: 1,
  },
  "sleep_duration": {
    key: "sleep_duration",
    unit: "min",
    aggregation: "sum",
    category: "sleep",
    labelDe: "Schlafdauer",
    labelEn: "Sleep duration",
    sources: ["apple_health", "whoop"],
    aliases: ["sleep_analysis", "sleep", "sleep_duration_hours", "sleep_asleep_duration"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "sleep_duration_deep": {
    key: "sleep_duration_deep",
    unit: "min",
    aggregation: "sum",
    category: "sleep",
    labelDe: "Tiefschlaf",
    labelEn: "Deep sleep",
    sources: ["apple_health", "whoop"],
    aliases: ["sleep_deep_duration"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "sleep_duration_rem": {
    key: "sleep_duration_rem",
    unit: "min",
    aggregation: "sum",
    category: "sleep",
    labelDe: "REM-Schlaf",
    labelEn: "REM sleep",
    sources: ["apple_health", "whoop"],
    aliases: ["sleep_rem_duration"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "sleep_duration_light": {
    key: "sleep_duration_light",
    unit: "min",
    aggregation: "sum",
    category: "sleep",
    labelDe: "Leichtschlaf",
    labelEn: "Light sleep",
    sources: ["apple_health", "whoop"],
    aliases: ["sleep_core_duration", "sleep_light_duration"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "sleep_duration_awake": {
    key: "sleep_duration_awake",
    unit: "min",
    aggregation: "sum",
    category: "sleep",
    labelDe: "Wachzeit",
    labelEn: "Awake time",
    sources: ["apple_health", "whoop"],
    aliases: ["sleep_awake_duration"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "sleep_duration_in_bed": {
    key: "sleep_duration_in_bed",
    unit: "min",
    aggregation: "sum",
    category: "sleep",
    labelDe: "Zeit im Bett",
    labelEn: "Time in bed",
    sources: ["apple_health", "whoop"],
    aliases: ["sleep_inbed_duration", "sleep_in_bed_duration"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "sleep_efficiency": {
    key: "sleep_efficiency",
    unit: "%",
    aggregation: "average",
    category: "sleep",
    labelDe: "Schlafeffizienz",
    labelEn: "Sleep efficiency",
    sources: ["whoop"],
    aliases: ["sleep_efficiency_percentage"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "whoop_sleep_need": {
    key: "whoop_sleep_need",
    unit: "min",
    aggregation: "average",
    category: "sleep",
    labelDe: "Whoop-Schlafbedarf",
    labelEn: "WHOOP sleep need",
    sources: ["whoop"],
    aliases: ["sleep_need_minutes"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "whoop_sleep_debt": {
    key: "whoop_sleep_debt",
    unit: "min",
    aggregation: "average",
    category: "sleep",
    labelDe: "Whoop-Schlafdefizit",
    labelEn: "WHOOP sleep debt",
    sources: ["whoop"],
    aliases: ["sleep_debt_minutes"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "whoop_sleep_consistency": {
    key: "whoop_sleep_consistency",
    unit: "%",
    aggregation: "average",
    category: "sleep",
    labelDe: "Whoop-Schlafbeständigkeit",
    labelEn: "WHOOP sleep consistency",
    sources: ["whoop"],
    aliases: ["sleep_consistency_percentage"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "sleep_nap_count": {
    key: "sleep_nap_count",
    unit: "count",
    aggregation: "sum",
    category: "sleep",
    labelDe: "Nickerchen",
    labelEn: "Naps",
    sources: ["whoop"],
    aliases: ["naps"],
    plausibleMin: 0.0,
    plausibleMax: 50.0,
    precision: 0,
  },
  "whoop_sleep_performance": {
    key: "whoop_sleep_performance",
    unit: "%",
    aggregation: "average",
    category: "sleep",
    labelDe: "Whoop Sleep Performance",
    labelEn: "Whoop sleep performance",
    sources: ["whoop"],
    aliases: ["sleep_performance_percentage", "whoop_sleep_performance_percent"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "whoop_recovery_score": {
    key: "whoop_recovery_score",
    unit: "%",
    aggregation: "average",
    category: "sleep",
    labelDe: "Whoop Recovery",
    labelEn: "Whoop recovery",
    sources: ["whoop"],
    aliases: ["recovery_score"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 0,
  },
  "oura_sleep_score": {
    key: "oura_sleep_score",
    unit: "index",
    aggregation: "average",
    category: "sleep",
    labelDe: "Oura Sleep Score",
    labelEn: "Oura sleep score",
    sources: ["oura"],
    aliases: ["sleep_score"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 0,
  },
  "oura_readiness_score": {
    key: "oura_readiness_score",
    unit: "index",
    aggregation: "average",
    category: "sleep",
    labelDe: "Oura Readiness Score",
    labelEn: "Oura readiness score",
    sources: ["oura"],
    aliases: ["readiness_score"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 0,
  },
  "oura_activity_score": {
    key: "oura_activity_score",
    unit: "index",
    aggregation: "average",
    category: "activity",
    labelDe: "Oura Activity Score",
    labelEn: "Oura activity score",
    sources: ["oura"],
    aliases: ["activity_score"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 0,
  },
  "body_weight": {
    key: "body_weight",
    unit: "kg",
    aggregation: "last",
    category: "body",
    labelDe: "Körpergewicht",
    labelEn: "Body weight",
    sources: ["apple_health"],
    aliases: ["body_mass", "weight"],
    plausibleMin: 20.0,
    plausibleMax: 400.0,
    precision: 1,
  },
  "body_fat": {
    key: "body_fat",
    unit: "%",
    aggregation: "last",
    category: "body",
    labelDe: "Körperfettanteil",
    labelEn: "Body fat",
    sources: ["apple_health"],
    aliases: ["body_fat_percentage"],
    plausibleMin: 1.0,
    plausibleMax: 70.0,
    precision: 1,
  },
  "vo2_max": {
    key: "vo2_max",
    unit: "mL/kg/min",
    aggregation: "last",
    category: "body",
    labelDe: "VO2max",
    labelEn: "VO2 max",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 10.0,
    plausibleMax: 95.0,
    precision: 1,
  },
  "skin_temperature": {
    key: "skin_temperature",
    unit: "°C",
    aggregation: "average",
    category: "body",
    labelDe: "Hauttemperatur",
    labelEn: "Skin temperature",
    sources: ["whoop"],
    aliases: ["skin_temp_celsius"],
    plausibleMin: 20.0,
    plausibleMax: 45.0,
    precision: 1,
  },
  "nutrition_energy": {
    key: "nutrition_energy",
    unit: "kcal",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Kalorien",
    labelEn: "Calories",
    sources: ["yazio", "apple_health"],
    aliases: ["calories", "yazio_calories", "calories_consumed", "dietary_energy_consumed", "nutrition_calories_kcal"],
    plausibleMin: 0.0,
    plausibleMax: 20000.0,
    precision: 0,
  },
  "nutrition_protein": {
    key: "nutrition_protein",
    unit: "g",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Protein",
    labelEn: "Protein",
    sources: ["yazio"],
    aliases: ["protein", "yazio_protein", "nutrition_protein_g"],
    plausibleMin: 0.0,
    plausibleMax: 1000.0,
    precision: 0,
  },
  "nutrition_carbohydrates": {
    key: "nutrition_carbohydrates",
    unit: "g",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Kohlenhydrate",
    labelEn: "Carbohydrates",
    sources: ["yazio"],
    aliases: ["carbohydrates", "carbs", "yazio_carbs", "nutrition_carbs_g"],
    plausibleMin: 0.0,
    plausibleMax: 2000.0,
    precision: 0,
  },
  "nutrition_fat": {
    key: "nutrition_fat",
    unit: "g",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Fett",
    labelEn: "Fat",
    sources: ["yazio"],
    aliases: ["fat", "yazio_fat", "nutrition_fat_g"],
    plausibleMin: 0.0,
    plausibleMax: 1000.0,
    precision: 0,
  },
  "nutrition_fiber": {
    key: "nutrition_fiber",
    unit: "g",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Ballaststoffe",
    labelEn: "Fibre",
    sources: ["yazio"],
    aliases: ["fiber", "yazio_fiber", "nutrition_fiber_g"],
    plausibleMin: 0.0,
    plausibleMax: 500.0,
    precision: 0,
  },
  "nutrition_meal_energy": {
    key: "nutrition_meal_energy",
    unit: "kcal",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Kalorien je Mahlzeit",
    labelEn: "Calories per meal",
    sources: ["yazio"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 20000.0,
    precision: 0,
  },
  "nutrition_item_energy": {
    key: "nutrition_item_energy",
    unit: "kcal",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Kalorien je Eintrag",
    labelEn: "Calories per item",
    sources: ["yazio"],
    aliases: ["consumed_item_calories"],
    plausibleMin: 0.0,
    plausibleMax: 20000.0,
    precision: 0,
  },
  "nutrition_item_amount": {
    key: "nutrition_item_amount",
    unit: "g",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Menge je Eintrag",
    labelEn: "Amount per item",
    sources: ["yazio"],
    aliases: ["consumed_product"],
    plausibleMin: 0.0,
    plausibleMax: 100000.0,
    precision: 0,
  },
  "nutrition_recipe_portions": {
    key: "nutrition_recipe_portions",
    unit: "count",
    aggregation: "sum",
    category: "nutrition",
    labelDe: "Rezeptportionen",
    labelEn: "Recipe portions",
    sources: ["yazio"],
    aliases: ["consumed_recipe_portion"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "workout_duration": {
    key: "workout_duration",
    unit: "min",
    aggregation: "sum",
    category: "workout",
    labelDe: "Trainingsdauer",
    labelEn: "Workout duration",
    sources: ["apple_health", "whoop"],
    aliases: ["whoop_workout_duration_minutes"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "workout_distance": {
    key: "workout_distance",
    unit: "km",
    aggregation: "sum",
    category: "workout",
    labelDe: "Trainingsdistanz",
    labelEn: "Workout distance",
    sources: ["apple_health", "whoop"],
    aliases: ["workout_distance_meter"],
    plausibleMin: 0.0,
    plausibleMax: 500.0,
    precision: 2,
  },
  "workout_energy": {
    key: "workout_energy",
    unit: "kcal",
    aggregation: "sum",
    category: "workout",
    labelDe: "Trainingsenergie",
    labelEn: "Workout energy",
    sources: ["apple_health", "whoop"],
    aliases: ["workout_active_energy", "workout_kilojoule"],
    plausibleMin: 0.0,
    plausibleMax: 15000.0,
    precision: 0,
  },
  "workout_heart_rate_average": {
    key: "workout_heart_rate_average",
    unit: "bpm",
    aggregation: "average",
    category: "workout",
    labelDe: "Trainingspuls (Durchschnitt)",
    labelEn: "Workout heart rate (average)",
    sources: ["apple_health", "whoop"],
    aliases: ["workout_avg_heart_rate", "workout_average_heart_rate"],
    plausibleMin: 40.0,
    plausibleMax: 230.0,
    precision: 0,
  },
  "workout_heart_rate_max": {
    key: "workout_heart_rate_max",
    unit: "bpm",
    aggregation: "max",
    category: "workout",
    labelDe: "Trainingspuls (Maximum)",
    labelEn: "Workout heart rate (max)",
    sources: ["apple_health", "whoop"],
    aliases: ["workout_max_heart_rate"],
    plausibleMin: 40.0,
    plausibleMax: 240.0,
    precision: 0,
  },
  "workout_heart_rate_zone_1": {
    key: "workout_heart_rate_zone_1",
    unit: "%",
    aggregation: "average",
    category: "workout",
    labelDe: "Trainingspuls Zone 1",
    labelEn: "Workout heart-rate zone 1",
    sources: ["whoop"],
    aliases: ["heart_rate_zone_1"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "workout_heart_rate_zone_2": {
    key: "workout_heart_rate_zone_2",
    unit: "%",
    aggregation: "average",
    category: "workout",
    labelDe: "Trainingspuls Zone 2",
    labelEn: "Workout heart-rate zone 2",
    sources: ["whoop"],
    aliases: ["heart_rate_zone_2"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "workout_heart_rate_zone_3": {
    key: "workout_heart_rate_zone_3",
    unit: "%",
    aggregation: "average",
    category: "workout",
    labelDe: "Trainingspuls Zone 3",
    labelEn: "Workout heart-rate zone 3",
    sources: ["whoop"],
    aliases: ["heart_rate_zone_3"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "workout_heart_rate_zone_4": {
    key: "workout_heart_rate_zone_4",
    unit: "%",
    aggregation: "average",
    category: "workout",
    labelDe: "Trainingspuls Zone 4",
    labelEn: "Workout heart-rate zone 4",
    sources: ["whoop"],
    aliases: ["heart_rate_zone_4"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "workout_heart_rate_zone_5": {
    key: "workout_heart_rate_zone_5",
    unit: "%",
    aggregation: "average",
    category: "workout",
    labelDe: "Trainingspuls Zone 5",
    labelEn: "Workout heart-rate zone 5",
    sources: ["whoop"],
    aliases: ["heart_rate_zone_5"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 1,
  },
  "workout_steps": {
    key: "workout_steps",
    unit: "count",
    aggregation: "sum",
    category: "workout",
    labelDe: "Schritte (Training)",
    labelEn: "Steps (workout)",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 200000.0,
    precision: 0,
  },
  "workout_speed_average": {
    key: "workout_speed_average",
    unit: "km/h",
    aggregation: "average",
    category: "workout",
    labelDe: "Geschwindigkeit (Durchschnitt)",
    labelEn: "Speed (average)",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 120.0,
    precision: 1,
  },
  "workout_speed_max": {
    key: "workout_speed_max",
    unit: "km/h",
    aggregation: "max",
    category: "workout",
    labelDe: "Geschwindigkeit (Maximum)",
    labelEn: "Speed (max)",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 200.0,
    precision: 1,
  },
  "workout_cadence": {
    key: "workout_cadence",
    unit: "spm",
    aggregation: "average",
    category: "workout",
    labelDe: "Schrittfrequenz",
    labelEn: "Cadence",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 300.0,
    precision: 0,
  },
  "workout_cycling_cadence": {
    key: "workout_cycling_cadence",
    unit: "rpm",
    aggregation: "average",
    category: "workout",
    labelDe: "Trittfrequenz (Radfahren)",
    labelEn: "Cycling cadence",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 250.0,
    precision: 0,
  },
  "workout_cycling_power": {
    key: "workout_cycling_power",
    unit: "W",
    aggregation: "average",
    category: "workout",
    labelDe: "Leistung (Radfahren)",
    labelEn: "Cycling power",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 2000.0,
    precision: 0,
  },
  "workout_elevation_gain": {
    key: "workout_elevation_gain",
    unit: "m",
    aggregation: "sum",
    category: "workout",
    labelDe: "Höhenmeter (Aufstieg)",
    labelEn: "Elevation gain",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 15000.0,
    precision: 0,
  },
  "workout_elevation_loss": {
    key: "workout_elevation_loss",
    unit: "m",
    aggregation: "sum",
    category: "workout",
    labelDe: "Höhenmeter (Abstieg)",
    labelEn: "Elevation loss",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 15000.0,
    precision: 0,
  },
  "workout_lap_length": {
    key: "workout_lap_length",
    unit: "m",
    aggregation: "last",
    category: "workout",
    labelDe: "Bahnlänge",
    labelEn: "Lap length",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 10000.0,
    precision: 1,
  },
  "workout_swim_cadence": {
    key: "workout_swim_cadence",
    unit: "spm",
    aggregation: "average",
    category: "workout",
    labelDe: "Schlagfrequenz (Schwimmen)",
    labelEn: "Swim cadence",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 200.0,
    precision: 0,
  },
  "workout_swimming_strokes": {
    key: "workout_swimming_strokes",
    unit: "count",
    aggregation: "sum",
    category: "workout",
    labelDe: "Schwimmzüge",
    labelEn: "Swimming strokes",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 100000.0,
    precision: 0,
  },
  "workout_intensity": {
    key: "workout_intensity",
    unit: "MET",
    aggregation: "average",
    category: "workout",
    labelDe: "Intensität",
    labelEn: "Intensity",
    sources: ["apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 30.0,
    precision: 1,
  },
  "whoop_workout_strain": {
    key: "whoop_workout_strain",
    unit: "index",
    aggregation: "max",
    category: "workout",
    labelDe: "Whoop Strain (Training)",
    labelEn: "Whoop strain (workout)",
    sources: ["whoop"],
    aliases: ["workout_strain"],
    plausibleMin: 0.0,
    plausibleMax: 21.0,
    precision: 1,
  },
  "strength_set_weight": {
    key: "strength_set_weight",
    unit: "kg",
    aggregation: "max",
    category: "strength",
    labelDe: "Satzgewicht",
    labelEn: "Set weight",
    sources: ["streak"],
    aliases: ["workout_set_weight_kg"],
    plausibleMin: 0.0,
    plausibleMax: 1000.0,
    precision: 1,
  },
  "strength_set_reps": {
    key: "strength_set_reps",
    unit: "count",
    aggregation: "sum",
    category: "strength",
    labelDe: "Wiederholungen",
    labelEn: "Repetitions",
    sources: ["streak"],
    aliases: ["workout_set_reps"],
    plausibleMin: 0.0,
    plausibleMax: 1000.0,
    precision: 0,
  },
  "strength_set_volume": {
    key: "strength_set_volume",
    unit: "kg",
    aggregation: "sum",
    category: "strength",
    labelDe: "Satzvolumen",
    labelEn: "Set volume",
    sources: ["streak"],
    aliases: ["workout_set_volume"],
    plausibleMin: 0.0,
    plausibleMax: 100000.0,
    precision: 1,
  },
  "strength_set_heart_rate_max": {
    key: "strength_set_heart_rate_max",
    unit: "bpm",
    aggregation: "max",
    category: "strength",
    labelDe: "Maximalpuls im Satz",
    labelEn: "Set peak heart rate",
    sources: ["streak"],
    aliases: ["workout_set_heart_rate_max"],
    plausibleMin: 40.0,
    plausibleMax: 240.0,
    precision: 0,
  },
  "strength_session_volume": {
    key: "strength_session_volume",
    unit: "kg",
    aggregation: "sum",
    category: "strength",
    labelDe: "Trainingsvolumen",
    labelEn: "Session volume",
    sources: ["streak"],
    aliases: ["workout_total_volume"],
    plausibleMin: 0.0,
    plausibleMax: 1000000.0,
    precision: 0,
  },
  "strength_session_sets": {
    key: "strength_session_sets",
    unit: "count",
    aggregation: "sum",
    category: "strength",
    labelDe: "Sätze",
    labelEn: "Sets",
    sources: ["streak"],
    aliases: ["workout_total_sets"],
    plausibleMin: 0.0,
    plausibleMax: 500.0,
    precision: 0,
  },
  "location_point": {
    key: "location_point",
    unit: "count",
    aggregation: "sum",
    category: "location",
    labelDe: "Standortpunkte",
    labelEn: "Location points",
    sources: ["dawarich", "apple_health"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 1.0,
    precision: 0,
  },
  "location_latitude": {
    key: "location_latitude",
    unit: "°",
    aggregation: "last",
    category: "location",
    labelDe: "Breitengrad",
    labelEn: "Latitude",
    sources: ["dawarich"],
    aliases: [],
    plausibleMin: -90.0,
    plausibleMax: 90.0,
    precision: 6,
  },
  "location_longitude": {
    key: "location_longitude",
    unit: "°",
    aggregation: "last",
    category: "location",
    labelDe: "Längengrad",
    labelEn: "Longitude",
    sources: ["dawarich"],
    aliases: [],
    plausibleMin: -180.0,
    plausibleMax: 180.0,
    precision: 6,
  },
  "calendar_event_count": {
    key: "calendar_event_count",
    unit: "count",
    aggregation: "sum",
    category: "calendar",
    labelDe: "Termine",
    labelEn: "Calendar events",
    sources: ["calendar"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 200.0,
    precision: 0,
  },
  "calendar_busy_duration": {
    key: "calendar_busy_duration",
    unit: "min",
    aggregation: "sum",
    category: "calendar",
    labelDe: "Belegte Zeit",
    labelEn: "Busy time",
    sources: ["calendar"],
    aliases: ["calendar_busy_minutes"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "calendar_meeting_duration": {
    key: "calendar_meeting_duration",
    unit: "min",
    aggregation: "sum",
    category: "calendar",
    labelDe: "Termindauer",
    labelEn: "Meeting duration",
    sources: ["calendar"],
    aliases: ["calendar_meeting_duration_minutes"],
    plausibleMin: 0.0,
    plausibleMax: 1440.0,
    precision: 0,
  },
  "weather_temperature": {
    key: "weather_temperature",
    unit: "°C",
    aggregation: "average",
    category: "environment",
    labelDe: "Außentemperatur",
    labelEn: "Outdoor temperature",
    sources: ["weather"],
    aliases: ["weather_temperature_c"],
    plausibleMin: -70.0,
    plausibleMax: 60.0,
    precision: 1,
  },
  "weather_temperature_apparent": {
    key: "weather_temperature_apparent",
    unit: "°C",
    aggregation: "average",
    category: "environment",
    labelDe: "Gefühlte Temperatur",
    labelEn: "Apparent temperature",
    sources: ["weather"],
    aliases: ["weather_apparent_temperature_c"],
    plausibleMin: -80.0,
    plausibleMax: 70.0,
    precision: 1,
  },
  "weather_humidity": {
    key: "weather_humidity",
    unit: "%",
    aggregation: "average",
    category: "environment",
    labelDe: "Luftfeuchtigkeit",
    labelEn: "Humidity",
    sources: ["weather"],
    aliases: ["weather_humidity_pct"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 0,
  },
  "weather_precipitation": {
    key: "weather_precipitation",
    unit: "mm",
    aggregation: "sum",
    category: "environment",
    labelDe: "Niederschlag",
    labelEn: "Precipitation",
    sources: ["weather"],
    aliases: ["weather_precipitation_mm"],
    plausibleMin: 0.0,
    plausibleMax: 500.0,
    precision: 1,
  },
  "weather_pressure": {
    key: "weather_pressure",
    unit: "hPa",
    aggregation: "average",
    category: "environment",
    labelDe: "Luftdruck",
    labelEn: "Air pressure",
    sources: ["weather"],
    aliases: ["weather_pressure_hpa"],
    plausibleMin: 800.0,
    plausibleMax: 1100.0,
    precision: 0,
  },
  "weather_wind_speed": {
    key: "weather_wind_speed",
    unit: "km/h",
    aggregation: "average",
    category: "environment",
    labelDe: "Windgeschwindigkeit",
    labelEn: "Wind speed",
    sources: ["weather"],
    aliases: ["weather_wind_speed_kmh"],
    plausibleMin: 0.0,
    plausibleMax: 500.0,
    precision: 1,
  },
  "weather_cloud_cover": {
    key: "weather_cloud_cover",
    unit: "%",
    aggregation: "average",
    category: "environment",
    labelDe: "Bewölkung",
    labelEn: "Cloud cover",
    sources: ["weather"],
    aliases: ["weather_cloud_cover_pct"],
    plausibleMin: 0.0,
    plausibleMax: 100.0,
    precision: 0,
  },
  "weather_uv_index": {
    key: "weather_uv_index",
    unit: "index",
    aggregation: "max",
    category: "environment",
    labelDe: "UV-Index",
    labelEn: "UV index",
    sources: ["weather"],
    aliases: [],
    plausibleMin: 0.0,
    plausibleMax: 20.0,
    precision: 1,
  },
};

/** Legacy or provider-specific name -> canonical key. */
export const METRIC_ALIASES: Record<string, string> = {
  "active_energy": "energy_active",
  "active_energy_burned": "energy_active",
  "activity_score": "oura_activity_score",
  "apple_exercise_time": "exercise_duration",
  "apple_stand_time": "stand_duration",
  "basal_energy_burned": "energy_resting",
  "body_fat_percentage": "body_fat",
  "body_mass": "body_weight",
  "calendar_busy_minutes": "calendar_busy_duration",
  "calendar_meeting_duration_minutes": "calendar_meeting_duration",
  "calories": "nutrition_energy",
  "calories_consumed": "nutrition_energy",
  "carbohydrates": "nutrition_carbohydrates",
  "carbs": "nutrition_carbohydrates",
  "consumed_item_calories": "nutrition_item_energy",
  "consumed_product": "nutrition_item_amount",
  "consumed_recipe_portion": "nutrition_recipe_portions",
  "cycle_average_heart_rate": "heart_rate_average",
  "cycle_kilojoule": "energy_total",
  "diastolic": "blood_pressure_diastolic",
  "dietary_energy_consumed": "nutrition_energy",
  "distance_walking_running": "distance",
  "fat": "nutrition_fat",
  "fiber": "nutrition_fiber",
  "heart_rate_variability_sdnn": "hrv_sdnn",
  "heart_rate_zone_1": "workout_heart_rate_zone_1",
  "heart_rate_zone_2": "workout_heart_rate_zone_2",
  "heart_rate_zone_3": "workout_heart_rate_zone_3",
  "heart_rate_zone_4": "workout_heart_rate_zone_4",
  "heart_rate_zone_5": "workout_heart_rate_zone_5",
  "hrv": "hrv_sdnn",
  "hrv_rmssd_milli": "hrv_rmssd",
  "max_heart_rate": "heart_rate_max",
  "naps": "sleep_nap_count",
  "nutrition_calories_kcal": "nutrition_energy",
  "nutrition_carbs_g": "nutrition_carbohydrates",
  "nutrition_fat_g": "nutrition_fat",
  "nutrition_fiber_g": "nutrition_fiber",
  "nutrition_protein_g": "nutrition_protein",
  "oxygen_saturation": "blood_oxygen",
  "protein": "nutrition_protein",
  "readiness_score": "oura_readiness_score",
  "recovery_score": "whoop_recovery_score",
  "resting_energy": "energy_resting",
  "resting_heart_rate": "heart_rate_resting",
  "resting_heart_rate_bpm": "heart_rate_resting",
  "resting_hr": "heart_rate_resting",
  "skin_temp_celsius": "skin_temperature",
  "sleep": "sleep_duration",
  "sleep_analysis": "sleep_duration",
  "sleep_asleep_duration": "sleep_duration",
  "sleep_awake_duration": "sleep_duration_awake",
  "sleep_consistency_percentage": "whoop_sleep_consistency",
  "sleep_core_duration": "sleep_duration_light",
  "sleep_debt_minutes": "whoop_sleep_debt",
  "sleep_deep_duration": "sleep_duration_deep",
  "sleep_duration_hours": "sleep_duration",
  "sleep_efficiency_percentage": "sleep_efficiency",
  "sleep_in_bed_duration": "sleep_duration_in_bed",
  "sleep_inbed_duration": "sleep_duration_in_bed",
  "sleep_light_duration": "sleep_duration_light",
  "sleep_need_minutes": "whoop_sleep_need",
  "sleep_performance_percentage": "whoop_sleep_performance",
  "sleep_rem_duration": "sleep_duration_rem",
  "sleep_score": "oura_sleep_score",
  "spo2": "blood_oxygen",
  "spo2_percentage": "blood_oxygen",
  "step_count": "steps",
  "steps_count": "steps",
  "strain": "whoop_strain",
  "systolic": "blood_pressure_systolic",
  "walking_heart_rate_average": "heart_rate_walking_average",
  "walking_running_distance": "distance",
  "weather_apparent_temperature_c": "weather_temperature_apparent",
  "weather_cloud_cover_pct": "weather_cloud_cover",
  "weather_humidity_pct": "weather_humidity",
  "weather_precipitation_mm": "weather_precipitation",
  "weather_pressure_hpa": "weather_pressure",
  "weather_temperature_c": "weather_temperature",
  "weather_wind_speed_kmh": "weather_wind_speed",
  "weight": "body_weight",
  "whoop_sleep_performance_percent": "whoop_sleep_performance",
  "whoop_workout_duration_minutes": "workout_duration",
  "workout_active_energy": "workout_energy",
  "workout_average_heart_rate": "workout_heart_rate_average",
  "workout_avg_heart_rate": "workout_heart_rate_average",
  "workout_distance_meter": "workout_distance",
  "workout_kilojoule": "workout_energy",
  "workout_max_heart_rate": "workout_heart_rate_max",
  "workout_set_heart_rate_max": "strength_set_heart_rate_max",
  "workout_set_reps": "strength_set_reps",
  "workout_set_volume": "strength_set_volume",
  "workout_set_weight_kg": "strength_set_weight",
  "workout_strain": "whoop_workout_strain",
  "workout_total_sets": "strength_session_sets",
  "workout_total_volume": "strength_session_volume",
  "yazio_calories": "nutrition_energy",
  "yazio_carbs": "nutrition_carbohydrates",
  "yazio_fat": "nutrition_fat",
  "yazio_fiber": "nutrition_fiber",
  "yazio_protein": "nutrition_protein",
};

/** Prefixes under which unregistered metric names are legal. */
export const NAMESPACES: MetricNamespace[] = [
  {
    prefix: "home_assistant_",
    category: "home",
    labelDe: "Home Assistant",
    labelEn: "Home Assistant",
  },
  {
    prefix: "apple_health_",
    category: "activity",
    labelDe: "Apple Health (nicht katalogisiert)",
    labelEn: "Apple Health (uncatalogued)",
  },
  {
    prefix: "custom_",
    category: "custom",
    labelDe: "Eigene Metrik",
    labelEn: "Custom metric",
  },
];

/** Canonical keys, in registry order. */
export const CANONICAL_KEYS: string[] = Object.keys(METRIC_CATALOG);

/** Canonical key for a possibly legacy name, or null if the registry has neither. */
export function canonicalMetricType(raw: string): string | null {
  const name = (raw ?? "").trim();
  if (name in METRIC_CATALOG) return name;
  if (name in METRIC_ALIASES) return METRIC_ALIASES[name];
  return NAMESPACES.some((ns) => name.startsWith(ns.prefix) && name.length > ns.prefix.length)
    ? name
    : null;
}

/** The definition for a metric name, or null for a namespaced or unknown one. */
export function resolveMetric(raw: string): MetricDefinition | null {
  const name = (raw ?? "").trim();
  if (name in METRIC_CATALOG) return METRIC_CATALOG[name];
  const canonical = METRIC_ALIASES[name];
  return canonical ? METRIC_CATALOG[canonical] : null;
}

/**
 * Something displayable for any metric name — a catalogued definition, a label
 * derived from the namespace suffix, or the raw name for a metric the registry has
 * never heard of (a tenant's older rows survive a catalog change that way).
 */
export function describeMetric(raw: string, locale: "de" | "en" = "de"): {
  label: string;
  unit: string;
  aggregation: Aggregation;
  precision: number;
} {
  const definition = resolveMetric(raw);
  if (definition) {
    return {
      label: locale === "de" ? definition.labelDe : definition.labelEn,
      unit: definition.unit,
      aggregation: definition.aggregation,
      precision: definition.precision,
    };
  }

  const name = (raw ?? "").trim();
  const namespace = NAMESPACES.find(
    (ns) => name.startsWith(ns.prefix) && name.length > ns.prefix.length,
  );
  const readable = (namespace ? name.slice(namespace.prefix.length) : name)
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();

  return { label: readable || name, unit: "", aggregation: "average", precision: 1 };
}
