"""Generate the importer contract catalog from ``importer.contract.json`` files."""

from __future__ import annotations

import argparse
from typing import Any

try:
    from tools.importer_contracts import REPO_ROOT, load_contracts
except ModuleNotFoundError:  # Direct execution puts tools/ rather than the repo on sys.path.
    from importer_contracts import REPO_ROOT, load_contracts

OUTPUT = REPO_ROOT / "docs" / "importer-contracts.md"


def _source_link(source: dict[str, Any]) -> str:
    reference = source["reference"]
    schema = source.get("schema")
    label = f"source ({schema})" if schema else "source"
    if reference.startswith(("http://", "https://")):
        return f"[{label}]({reference})"
    return f"`{reference}`"


def _input_lines(contract: dict[str, Any]) -> list[str]:
    return [
        f"`{item['name']}` (`{item['format']}`; {_source_link(item['source_of_truth'])})"
        for item in contract["input_contracts"]
    ]


def render(contracts: list[dict[str, Any]]) -> str:
    """Render the deterministic Markdown catalog."""
    lines = [
        "# Importer contract catalog",
        "",
        "<!-- This file is generated by tools/generate_importer_contracts.py. -->",
        "",
        "Every importer has a versioned `importer.contract.json` at its service root.",
        "Those files are the repository source of truth for the supported input shapes,",
        "service boundary, normalized output metrics and execution capabilities. CI validates",
        "the contracts and this page is generated from them; edit the contract files rather",
        "than this page.",
        "",
        "OpenAPI is used as an upstream reference where a provider exposes it. It is not",
        "forced onto file exports: iCalendar follows RFC 5545, Apple Health exports XML",
        "archives, and WHOOP exports ZIP archives of CSV files. The contract format keeps",
        "all of these input types explicit without pretending they share an API schema.",
        "",
        "## Common guarantees",
        "",
        "All eight importers publish tenant-scoped events to NATS JetStream, do not access",
        "a database, fetch connector configuration through Core, propagate `X-Request-ID`,",
        "resolve metric names through the shared registry, and include an idempotency key.",
        "The metric list below is the set registered for that source; dynamic namespaces",
        "are shown separately where the user's installation determines the fields.",
        "",
    ]
    for contract in contracts:
        source_type = contract["source_type"]
        capabilities = contract["capabilities"]
        capability_text = (
            f"scheduled sync `{str(capabilities['scheduled_sync']).lower()}`, "
            f"webhook `{str(capabilities['webhook']).lower()}`, "
            f"file upload `{str(capabilities['file_upload']).lower()}`"
        )
        lines.extend(
            [
                f"## `{source_type}`",
                "",
                f"- Ingest subject: `{contract['ingest_subject']}`",
                f"- Task subject: `{contract['task_subject'] or 'not applicable (push/file source)'}`",
                f"- Entrypoint: `{contract['entrypoint']}`",
                f"- Capabilities: {capability_text}",
                "- Input contracts:",
            ]
        )
        lines.extend(f"  - {item}" for item in _input_lines(contract))
        metrics = ", ".join(f"`{metric}`" for metric in contract["metrics"]) or "none (dynamic only)"
        lines.append(f"- Registered metrics: {metrics}")
        namespaces = ", ".join(f"`{namespace}`" for namespace in contract["dynamic_namespaces"])
        if namespaces:
            lines.append(f"- Dynamic namespaces: {namespaces}")
        lines.extend(["", "The complete machine-readable contract is next to the importer service.", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated page is stale")
    args = parser.parse_args()
    rendered = render(load_contracts())
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is stale; run this generator")
            return 1
        print(f"{OUTPUT.relative_to(REPO_ROOT)} is current")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
